### ISSUE TITLE
How to change SKU for another language store? (multistore - sku attribute)

### ISSUE THREAD

**Issue by devzorg** [dweeves/magmi-git#122]
I have tried
sku,store
admin_value_sku,'admin'
translated_sku::[admin_value_sku],'store2'

But it creates a new product with SKU eq 'translated_sku::[admin_value_sku]'

**Comment by aholovan** [comment]
Hi @dweeves, could You, please recall is there a plugin to update sku (sku,new_sku columns). Maybe it was implemented since that time this issue discussed.
Thanks!
