### ISSUE TITLE
Duplicate Attribute Option Value 

### ISSUE THREAD

**Issue by webdlp** [dweeves/magmi-git#126]
I had duplicate attribute option value issue for configurable products. My website is running magento 1.901 and magmi 0.7.19a.  Everything seems running fine except duplicate attribute option values for configurable products. For example, I imported a configurable product with 5 colors (Blue, Gold, Green, Pink, Red) with configurable_attributes as color.  The product was imported successfully. But it also created three new but duplicate attribute option values for color (Blue, Gold, Pink), which I had set up before. The other two color option values (Green and Red) still used the original values without duplication, which are correct.  That is very weird.

I did not find Capital and white space issues. I also turned on value trimmer, which did not help. Therefore, I'd like to hear some advices from our magmi experts 

The following are plugins I used to import configurable products.

CSV Datasource (1.3.1) by Dweeves
On the fly category creator/importer (0.2.3) by Dweeves
Image attributes processor (1.0.25) by Dweeves
On the fly indexer (0.1.5) by Dweeves
Tier price importer (0.0.9a) by Dweeves,bepixeld
Generic mapper (0.0.6a) by Dweeves
Configurable Item processor (1.3.7a) by Dweeves
Standard Attribute Import (1.0.6) by Dweeves

Thanks!

**Comment by barryvdh** [comment]
I have a similar issue with the latest git version:
> Item (Mage_Eav_Model_Entity_Attribute_Option) with the same id "1234" already exist

Is this related? For example, admin = store_id 0, nl=1, en=2, de=3. After import, I should have 0, 2 and 3 as options, but for store 2 and 3, a duplicate option is added.. This will fail on the frontend and stop the search index..

**Comment by webdlp** [comment]
It has been almost half year past since I first had this problem.  

Recently, I started to change my template to the rwd template and had problem in color swatch for certain colors. These colors were exactly the same with the duplicate colors I had encountered several months ago with Magmi. Since the color swatch is not related to Magmi, I believed there was some difference between the colors worked and the colors did not work.  Finally, I found that those did not work had a white space in my database, which was created during attribute setup.  That explains why I had value trimmer but still had the duplicate issue. 
If you encounter the same problem, please check your database or backend to see whether your attribute option value has the white space, not just check the white space in CSV. That is the lesson I learned. 
Also, I'd like to thank dweeves for developing such a nice tool which make import such a easy job.

**Comment by satyaranjan1231984** [comment]
I am new in Magmi. I am facing a issue while going to import the configurable products. Duplicate attribute option value are getting inserted. I am using Magmi v0.7.21.
Please help me to resolved it.

**Comment by chetanbura** [comment]
I have a similar issue with the latest git version:

![attribute](https://cloud.githubusercontent.com/assets/8872016/13912086/27bf18de-ef5f-11e5-86e5-064cf5f427a7.png)

**Comment by dweeves** [comment]
It seems the values are really different , so no real duplicates.

"Alcaltel Lucent" <> "Alcatel-Lucent" ( - )
"Arista Networks" <> "AristaNetworks" (space)
"Aruba Networks" <> "ArubaNetworks" (space)
'Black Box" <> "BlackBox" (space)

2016-03-21 7:49 GMT+01:00 Chetan Bura <notifications@github.com>:

**Comment by apothegm** [comment]
I'm having a similar issue with: Mass Select/Multiselect Attribute value translater v1.0.1

I'm attempting to bulk add values to attributes using the following CSV data:
![image](https://cloud.githubusercontent.com/assets/12129089/15056414/74aec1dc-12df-11e6-8edb-a701e882e95b.png)

Maybe my CSV isn't formatted correctly? I'm not really sure, but I've not been able to find any documentation on this Utility. So I figured out the required columns by analyzing the code for massattr.php. (On an unrelated note, it kept saying Not Found when attempting to load the CSV so I had to add $params to initialize() on line 61).

But it ends up creating a duplicate entry in the eav_attribute_option_value table with the same Value.

I want to bulk add values for attributes, and specify both an "admin" value and a store view (ebay) value simultaneously. Or if I have to do this is in two imports, but how?

**Comment by apothegm** [comment]
I'd rather use the Mass Select Attribute value translater utility, but I also tried this with the regular Product importer by using the following CSV data:
![image](https://cloud.githubusercontent.com/assets/12129089/15057087/16238162-12e3-11e6-8369-64fe773bef09.png)

It creates the new value for ebay_condition_id, but it doesn't seem to process the second row setting the ebay view value of 1500. Even if I separate them into different imports, it doesn't add the store view value of 1500. 
According to this: http://wiki.magmi.org/index.php?title=Magmi_Behaviour_-_select_%26_multiselect_attributes
It should work. 

I'm using latest version off sourceforge: 0.7.22

**Comment by schwipps** [comment]
If it can help...

I've also been facing way too much duplicated entries in the attribute_option_value table and millions in catalog_product_attribute_pricing, causing the .ibdata file and import timing growing dangerously.

We finally discovered that duplicated entries were coming from unmanaged input values using special characters (such as ¾). As these values were not handled, "39¾" was becoming a new "39" entry, at each import.
Once these values were handled correctly, we could clean our tables selectively (only the problematic values), and get back to normal. Since, no more duplicated entries have been created, and the number of entries in tables keep reasonable.

Finally, if your database has been signifiticatibly growing, remember that truncate or delete data from tables won't drop your database weight. To get back to normal, you'll have to dump it, delete ibdata file and source it back.
