### ISSUE TITLE
Products always get assigned to Default Category

### ISSUE THREAD

**Issue by Centilitre** [dweeves/magmi-git#127]
Hi,

When I import a product with categories field set to: [Root Category 2]/cat1, the product will be assigned to the following 3 categories:
Default Category
Root Category 2
Root Category 2/cat1

Note that it is added to Default Category, which is not what I want. I want the product to be added to Root Category 2 and cat1 only. Is this a bug? How can I get around this?

**Comment by mag-extension** [comment]
Hi

I am using 0.7.21 but I still have above issue, categories are always created under the magento default root category and not assigned to my second root category, my store name is correct.
