### ISSUE TITLE
Create Permanent Redirect for old URL

### ISSUE THREAD

**Issue by Centilitre** [dweeves/magmi-git#153]
Hello,

I am using value replacer to create url_key values, using the method described in the wiki: http://wiki.magmi.org/index.php?title=Value_Replacer#Slugger

The problem is that it doesn't create Permanent Redirect for old URL. If this method is used in production website, it could create lots of 404. 

Any way to create Permanent Redirect?

**Comment by macrel** [comment]
Hi, I know this is a closed issue, so I don`t know if I`m right to put my comment here.

I have enabled on the fly indexer and I add url_rewrite = 1 to every item I import. However, whenever I try to import an existing product with a new url_key, it does change the URL key, but it does not add a URL rewrite.

If I go into url rewrite management then I do not see changes after importing the products. I do see those changes however when I reindex the catalog.

Does this mean the on the fly indexer is not working for me? I put some logging into the code and I can see it going by the code of this plugin, it just does not add rewrites. Or maybe it does and I only see it after reindexing, but in that case it does not add rewrites for old to new URL.

How can I fix this? PS, do I need shell_exec for the OTF indexer? I know this is mandatory for the Magmi reindexer to work, but my host does not allow shell_exec.. 

Hope you can help me out soon! Thanks in advance!

**Comment by macrel** [comment]
Hi dweeves, any ideas on my question above? Thanks! Please le me know if I need to open a new issue for this

**Comment by macrel** [comment]
Can someone let me know if Magmi is no longer under development / no longer supported?
