### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'sort_order' at row 

### ISSUE THREAD

**Issue by damirock** [dweeves/magmi-git#161]
Hi, @dweeves 

I wonder how it wasn't discussed before, but i'm constantly getting this error and have no clue why it happens. Please let me know if there's anything can be done with this problem

![image](https://cloud.githubusercontent.com/assets/10164052/5455805/e1efa7c6-854f-11e4-9ebf-266794e9fbaa.png)

**Comment by kunal1234gh** [comment]
HI @dweeves  ,

  How did you fix this error.

**Comment by manticorp** [comment]
Can I ask what the error was that caused this? I'm getting this error now, can't seem to figure out what's going wrong.

**Comment by AdamHughes** [comment]
@manticorp  @kunal1234gh 
here
https://github.com/dweeves/magmi-git/commit/6a49d8aa0ee685e394b2bedf2ed8fee5fab574ff

**Comment by kunal1234gh** [comment]
ok :)
I used older version of magmi it solved it

**Comment by manticorp** [comment]
Thanks @AdamHughes !

**Comment by massimoxma** [comment]
Hi all, i get the same error in magmi 0.7.19. I try the import in local server it's ok, but on online server i get the error 1264 why?

**Comment by massimoxma** [comment]
sorry version is 0.7.21

**Comment by AdamHughes** [comment]
@massimoxma Look at this commit https://github.com/dweeves/magmi-git/commit/6a49d8aa0ee685e394b2bedf2ed8fee5fab574ff

**Comment by johng339** [comment]
I got same error and update 6a49d8a commit but still not working .. what should I check more? Please help!

**Comment by bhushanpatil** [comment]
I got same error. I used 6a49d8a  and its working for me. Thank you guys for posting this.

**Comment by clementgamache** [comment]
This problem occurs when a value in a column is not valid, for example when the column is a Multiple Select attribute and the value is not in the possible options list.
