### ISSUE TITLE
Bundle items not showing after import bundle products

### ISSUE THREAD

**Issue by Arafathi** [dweeves/magmi-git#163]
Hi,
I imported 4000 bundle products through latest version Magmi bundle item processor and then fully re-indexed. Everything in admin manage product page is Ok and all bundle items are showing. But on front end, in the bundle product page, the bundle items (drop down) are not showing! But then after I open and save the product in backend, the drop down with all the items will appear.
Is there any fix for this problem so I don't have to open and save 4000 bundle products one by one?!

Thank you

**Comment by dweeves** [comment]
Fixed in latest Git!!!

now bundle processor correctly links items (thx igi8819) & also fills default values for structural fields.
