### ISSUE TITLE
Media Images not loading / working with url as source

### ISSUE THREAD

**Issue by zaffar-saffee** [dweeves/magmi-git#167]
1. I got a csv and got 10 image urls in that...
2. for each product 4 to 10 images are available (shouldn;t be any issue I believe)
3. no + sign is added
4. my mapping is like 
   - CMAP:imagen_grande_1 = "media_gallery"
   - CMAP:imagen_grande_2 = "media_gallery"
   - CMAP:imagen_grande_3 = "media_gallery"
   - CMAP:imagen_grande_4 = "media_gallery"
   - CMAP:imagen_grande_5 = "media_gallery"
   - CMAP:imagen_grande_6 = "media_gallery"
   - CMAP:imagen_grande_7 = "media_gallery"
   - CMAP:imagen_grande_8 = "media_gallery"
   - CMAP:imagen_grande_9 = "media_gallery"
   - CMAP:imagen_grande_10 = "media_gallery"

5. Actually, I got other feilds too including image, small_image, sku, etc, but they are working exactly as they are are supposed too... 

6. image, small_image, thumbnail is excluded, but I am manually un-excluding it using a sql query....

but it does not show in magento backend, or front end

though I disabled Magento cache, deleted it from ftp, cleared and recreated... re-indexed... everything I can think of..

can somebody guide me please??

**Comment by dweeves** [comment]
column mapping does not work this way. what you want to achieve is to "aggregate" values from some columns into another. for this use the "value replacer" plugin with the following items:

value to replace : media_gallery
new value for media_gallery:
> {{ implode(',',array({item.imagen_grande_1},{item.imagen_grande_2},{item.imagen_grande_3},{item.imagen_grande_4},{item.imagen_grande_5},{item.imagen_grande_6},{item.imagen_grande_7},{item.imagen_grande_8},{item.imagen_grande_9},{item.imagen_grande_10})) }}

**Comment by zaffar-saffee** [comment]
thanks dweeves, thanks for your help..
however, I did this task in a bit different ( or you can say the standard way as described in your documentation)
I Imploded all the 10 columns in to one and used ";" as glue for implode... thus I got only one field... and that worked perfectly..


thanks for you help and Guidance....

thanks again for such a marvelous application...
