### ISSUE TITLE
Seems like catalog_product_entity_varchar table is damaged

### ISSUE THREAD

**Issue by z3eman** [dweeves/magmi-git#218]
Hello,

I hope it's a correct place to post my issue. We get all our product into magento only by using magmi imports. 4 days ago we found out that the names of products after import were empty and tried to start import again. And then noticed, that it's not possible to save products name also by using magento backend even if it give a success message back "The product has been saved." 

So we found out nothing will be saved into catalog_product_entity_varchar table anymore. 

I know it's probably not magmi fault, but maybe someone knows how to fix it? 

I can update product name for existing products via sql query:
UPDATE `catalog_product_entity_varchar` 
SET VALUE='My test product' WHERE entity_id='34281' AND store_id= '0' AND attribute_id='71';

If I try to do some INSERTs, for example:
INSERT INTO `catalog_product_entity_varchar` (`entity_type_id`,`attribute_id`,`store_id`,`entity_id`,`value`) 
VALUES (4, 71, 0, 34281, 'My test product 1 2 3') 
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
this new value will be saved not for attribute 71 but 112 o_0

**Comment by z3eman** [comment]
Oh yes, we could fix it...

Maybe someone else one day will run into same problem...

The value_id catalog_product_entity_varchar reached it's limit 2147483647! So we changed it's data type from int to bigint and everything works again!

http://en.wikipedia.org/wiki/2147483647

**Comment by iamthemadz** [comment]
I have been getting the same issue lately I think. I can no longer save data with Magmi and the log will have this error 'warning:SKU somesku-123 - No varchar Attributes created for sku somesku-123'. But then if i run it again it will say that the sku already exists (using xcreate), however I dont have any of the products in the magento backend except for maybe 10, and non have names.
