### ISSUE TITLE
No varchar Attributes created for sku

### ISSUE THREAD

**Issue by iamthemadz** [dweeves/magmi-git#219]
I keep attempting to import data but Magmi only tells me the follow,

'No varchar Attributes created for sku {sku here}' 

I absolutely cannot figure out what is going on or where to begin lookiing

**Comment by AdamHughes** [comment]
@iamthemadz 
Post the first few lines of your CSV file

**Comment by iamthemadz** [comment]
I need to close the ticket. It turned out that the script was messing up the header of my csv. I barely noticed it, but when i did, it was a facepalm moment.

Date: Sat, 21 Mar 2015 05:48:08 -0700
