### ISSUE TITLE
Unsetting the option of a select attribute is not possible in mode 'create'

### ISSUE THREAD

**Issue by ckressibucher** [dweeves/magmi-git#237]
`create` mode is describe as "create new items &amp; update existing ones". So it should be possible to set the default attribute option ("unset" the selected option) of a select attribute. Unfortunately, I did not find a way to do it:

First tried "__MAGMI_DELETE__". Problem: Instead of deleteing the row from the catalog_product_entity_int table (this would be what I expect), it creates a new option with the literal value "__MAGMI_DELETE_". This happens because the "handleIntAttribute" method of the default attribute handler does not handel any 'magic values', but treat it as a normal value.

Second try: Setting the value to an empty string. (because this causes the `handleIntAttribute` method to return '__MAGMI_DELETE__', in which case the import engine would delete the rows). No luck here as well, as emtpy options are skipped if the mode is not "update".

In my opinion, this is a bug. My suggestion would be to modify the line
`if ($ivalue == "" && $this->mode != "update" && $tp == "int")` to `if ($ivalue == "" && $this->mode == "xcreate" && $tp == "int")` in the import engine.
(https://github.com/dweeves/magmi-git/blob/master/magmi/engines/magmi_productimportengine.php#L1020)

Another fix would be to somehow prevent inserting magic values as an attribute option in general. But this may have too many side effects, so I would suggest the fix in the product import engine.

**Comment by dweeves** [comment]
could you try with latest commit ?

**Comment by RiccardoB** [comment]
I tried to update my magmi to latest git and it looks like it updates the values of a dropdown attribute if the field is filled but it's not emptying it if you set the field as an empty string.

**Comment by RiccardoB** [comment]
I've followed the suggestion by @ckressibucher to edit the IF and now on "create" mode it empties the values of dropdown attributes when needed, by the way I don't know if this could break something else.
Do you have @dweeves any warning about skipping that continue also on create mode or it was just for a performance optimization?
