### ISSUE TITLE
erro when import simple product

### ISSUE THREAD

**Issue by cduarte** [dweeves/magmi-git#240]
Hi 

when i import a csv of simple product I receive a error message 
SKU TC00001AM_NOVA_LINHA - 19 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value -
SKU TC00001AM_NOVA_LINHA - 20 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value - ERROR ON RECORD #10
SKU TC00001AM_PORTABILIDADE - 21 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value -
SKU TC00001AM_PORTABILIDADE - 22 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value - ERROR ON RECORD #11
SKU TC00001AM_TROCA - 23 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value -
SKU TC00001AM_TROCA - 24 SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value - ERROR ON RECORD #12

.....

WHY?
Do you know how to fix?

Thanks

**Comment by cduarte** [comment]
resolved.
I am putting integer value (ID) ... And the correct is put the name of the value..
 need to put the

**Comment by mokanfar** [comment]
If you have an attribute field that is not a text field (IE dropdown/multiple select) and you supply field names in CSV that are not defined in Magento Backend, it will throw this error, so make sure to supply names that match what is in backend.
