### ISSUE TITLE
Setting Qty Increments

### ISSUE THREAD

**Issue by RiccardoB** [dweeves/magmi-git#244]
I tried to enable and set the Qty Increments using these columns:
```
use_config_enable_qty_increments => 0
enable_qty_increments => 1
use_config_qty_increments => 0
qty_increments => 100
```
but the fields in the products are not set (they keep using the default config setting).

Is there a bug or am I doing something wrong?
What are the fields to use for editing the Qty Increments of the inventory section?

**Comment by RiccardoB** [comment]
Anyone could point me to the file that should take care of these fields? So I can give it a better look.

**Comment by sbeuving** [comment]
Please use use_config_enable_qty_inc => 0 instead of use_config_enable_qty_increments => 0

magmi uses the column names of the cataloginventory_stock_item table to manage stock.
So use_config_enable_qty_inc should be used instead.

I have this working settings:
        use_config_enable_qty_inc => 0
        use_config_qty_increments => 0
        enable_qty_increments => 1
        qty_increments => 100

Please let me know if it works

**Comment by RiccardoB** [comment]
Thanks @sbeuving, using use_config_enable_qty_inc it works.

These settings should be added to a page of the official MagMi wiki.
