### ISSUE TITLE
URL key is not updating

### ISSUE THREAD

**Issue by chamalC** [dweeves/magmi-git#247]
hi,

I have imported some products and later needed to change the URL keys so I have prepared a CSV which contain SKUs and the new url keys (ie: sku,url_key) . But after successfully import (Update existing items only,skip new ones) and check with backend product URL keys but they are not changed , I have re index them all but still the same, then I have imported the same CSV file using advanced dataflow profiles and it is working fine URL keys changed as per the CSV by using dataflow profiles . So can you explain me why this is happening ?

regards
chamal

**Comment by pluckrose** [comment]
I have the same issue, it seems in the latest version of Magento 1.9 CE and 1.14 EE there is a new table in the database for the URL keys, so you will see them in the product but the actual URL is something like catalog/product/view/id/13777/.

**Comment by lexmustafin** [comment]
Hi,
Same problem here.

**Comment by pluckrose** [comment]
Hi Guys

I think I have a workaround for it which is the following (it seems to be working):

1. Truncate the catalog_product_url_key table
2. Run the query below

INSERT INTO catalog_product_entity_url_key (entity_type_id, attribute_id, store_id, entity_id, value) SELECT 4, 97, 0, entity_id, value FROM catalog_product_entity_varchar WHERE attribute_id = 97;

(Attribute 97 is the URL key in my case, not sure if this is always the same but I would presume so)

3. Check some products, some will be fine but I then encountered a new problem with the URL keys appended to the end of the internal URL i.e. catalog/product/view/id/13777/cats/are/fun/ .

So now, truncate the following tables: 
- core_url_rewrite
- enterprise_catalog_category_rewrite
- enterprise_catalog_product_rewrite
- enterprise_url_rewrite

enterprise_url_rewrite may not let you truncate the table so you have to delete all the rows instead (I did this in Sequek Pro but I imagine cmd line would just work.

4. Redindex from root $ php shell/redindexer.php --reindex -all
5. Clear Cache

Doing the above seems to have solved the issue, it's been a few weeks and the customer hasn't come back with anymore problem URLs.

I do seem to have come across another issue now though which is products not automatically going out of stock when reaching 0, if I go into the product in admin and just save it, it starts to work. I tried to mass update all affected products but no luck (much like with the URL issue). So I'm not sure if this is related or not but BUUHHHHHHHHHH.

Anyway I hope the above helps someone, TEST IT FIRST!

Come on Dweeves, SAVE US!

**Comment by pluckrose** [comment]
For some reason my numbered bullets change back to 1 when I have a break, they worked in preview mode!
