### ISSUE TITLE
1:String could not be parsed as XML 

### ISSUE THREAD

**Issue by unhidden** [dweeves/magmi-git#250]
Hi,

I had run magmi imports successfully - what an awesome tool!
I am not sure what happened or changed but I cannot do any import of any file. When runnung an import I get the following error:

MAGMI by dweeves - version:0.7.21
Running Magmi Product Import Engine v1.9 by dweeves
1:String could not be parsed as XML -
Import Ended 

and here is the trace.txt
=========================BEGIN======================
---- TRACE : 1 -----

---- DATE : 2015-05-06 12:53:25 ------

************************************

String could not be parsed as XML

*************************************

/inc/magmi_engine.php:525 - SimpleXMLElement->__construct

----------------------------------------

Array

(

[0] =>

)

/inc/magmi_engine.php:481 - Magmi_Engine->connectToMagento

----------------------------------------

Array

(

)

/web/magmi_run.php:44 - Magmi_Engine->run

----------------------------------------

Array

(

[0] => Array

(

[engine] => magmi_productimportengine:Magmi_ProductImportEngine

[ts] => 1430916795

[run] => import

[logfile] => progress.txt

[profile] => default_import

[mode] => update

[PHPSESSID] => f3b8fc77073748875d14073c8f646511

[__cfduid] => daa2d42796b9149a847973f1a1e7b59fd1430913597

)

)

+++++++++++++++++++++++++++++

CONTEXT DUMP

+++++++++++++++++++++++++++++

Magmi_ProductImportEngine Object

(

[attrinfo] => Array

(

)

[attrbytype] => Array

(

)

[attribute_sets] => Array

(

)

[prod_etype] =>

[default_asid] =>

[sidcache] => Array

(

)

[mode] => update

[_notattribs:Magmi_ProductImportEngine:private] => Array

(

)

[_attributehandlers:Magmi_ProductImportEngine:private] =>

[_current_row:Magmi_ProductImportEngine:private] =>

[_optidcache:Magmi_ProductImportEngine:private] =>

[_curitemids:Magmi_ProductImportEngine:private] => Array

(

[sku] =>

)

[_dstore:Magmi_ProductImportEngine:private] => Array

(

)

[_same:Magmi_ProductImportEngine:private] =>

[_extra_attrs:Magmi_ProductImportEngine:private] =>

[_profile:Magmi_ProductImportEngine:private] =>

[_sid_wsscope:Magmi_ProductImportEngine:private] => Array

(

)

[_sid_sscope:Magmi_ProductImportEngine:private] => Array

(

)

[_prodcols:Magmi_ProductImportEngine:private] => Array

(

)

[_stockcols:Magmi_ProductImportEngine:private] => Array

(

)

[_skustats:Magmi_ProductImportEngine:private] => Array

(

)

[_handlercache:Magmi_ProductImportEngine:private] => Array

(

)

[_conf:protected] => Magmi_Config Object

(

[_defaultconfigname:Magmi_Config:private] =>

[_basedir:protected] => /homepages/46/PATH_HIDDEN/htdocs/PATH_HIDDEN/magmi_bulk/conf

[_confname:protected] => magmi.ini

[_props:protected] => Array

(

[DATABASE] => Array

(

[connectivity] => localxml

[host] => HOST_NAME

[port] => 3306

[dbname] => DB_NAME

[user] => USER_ID

[password] => PASSWORD

[table_prefix] =>

)

[MAGENTO] => Array

(

[version] => 1.9.x

[basedir] => ../..

)

[GLOBAL] => Array

(

[step] => 0.5

[multiselect_sep] => ,

[dirmask] => 755

[filemask] => 644

)

)

[inifile] => /homepages/46/PATH_HIDDEN/htdocs/PATH_HIDDEN/magmi_bulk/conf/magmi.ini

[_specialchars:protected] => Array

(

["] => :DQUOTE:

['] => :SQUOTE:

[\t] => TAB

)

)

[_initialized:protected] => 1

[_exceptions:protected] => Array

(

[String could not be parsed as XML] => Array

(

[0] => 1

[1] => 1

)

)

[tprefix] =>

[_connected:protected] =>

[_activeplugins:protected] =>

[_pluginclasses:protected] =>

[_builtinplugins:protected] => Array

(

[itemprocessors] => /homepages/46/PATH_HIDDEN/htdocs/PATH_HIDDEN/magmi_bulk/plugins/inc/magmi_defaultattributehandler.php::Magmi_DefaultAttributeItemProcessor

)

[_ploop_callbacks:protected] => Array

(

)

[_excid:Magmi_Engine:private] => 1

[logger] => FileLogger Object

(

[_fname:protected] => /homepages/46/PATH_HIDDEN/htdocs/PATH_HIDDEN/magmi_bulk/state/progress.txt

)

[_timingcats:protected] => Array

(

)

[_db:protected] =>

[_debug:protected] =>

[_laststmt:protected] =>

[_use_stmt_cache:protected] => 1

[_nreq:protected] =>

[_indbtime:protected] =>

[_intrans:protected] =>

[prepared:protected] => Array

(

)

[_timecounter:protected] => TimeCounter Object

(

[_timingcats:protected] => Array

(

[db] => Array

(

[_counters] => Array

(

[requests] => 0

)

[_timers] => Array

(

)

)

)

[_defaultsrc:protected] => Magmi_ProductImportEngine

[_timingcontext:protected] => Array

(

)

)

[_tcats:protected] => db

)

+++++++++++++++++++++++++++++

END CONTEXT DUMP

+++++++++++++++++++++++++++++ 
===========================END===================

I tried playing around with the CSV file formats and tested the old ones that I used and worked but nothing works now.  

I would greatly appreciate some insight how to resolve this issue.

**Comment by dweeves** [comment]
It seems the magento directory path is not good or read access from magmi for local.xml does not work. could you try using a full path for magento directory ?

**Comment by unhidden** [comment]
YES!  somehow the path to Magento got reset it seems.  Tried everything else but hadn't thought of that.

Thanks a ton!
