### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by tim-bezhashvyly** [dweeves/magmi-git#308]
Converting tabs to spaces surprisingly introduced the following issue:

> PHP Notice:  Undefined variable: tname in /path/to/vendor/dweeves/magmi/magmi/engines/magmi_productimportengine.php on line 363

The reason is [here](https://github.com/dweeves/magmi-git/commit/7b45596174e05fa541752649e6b4c9daec1e0c7a#commitcomment-12538384).

**Comment by dweeves** [comment]
this has been fixed
