### ISSUE TITLE
Numeric value out of range: 167 Out of range value for column 'value_id' at row 1

### ISSUE THREAD

**Issue by stefano-crosatti** [dweeves/magmi-git#320]
I got 2 magento istance on a single instance of MariaDB.
Suddenly only 1 istance started to have problems with magmi import while the other run smootly.
The import is a simple CSV file that update the stocks and some minor data.

Here it is some sample lines of the CSV file:

store,website,sku,collana_id,collana_conclusa,qty,is_in_stock,esaurito,novita,magmi:delete
"admin","base","1","1915","1","0","0","1","0","0"
"admin","base","2","1915","1","0","0","1","0","0"
"admin","base","3","1915","1","0","0","1","0","0"
"admin","base","4","1915","1","0","0","1","0","0"
"admin","base","5","1912","1","0","0","0","0","0"
"admin","base","6","1915","1","1","1","0","0","0"
"admin","base","7","1912","1","0","0","1","0","0"
"admin","base","8","1915","1","0","0","1","0","0"
"admin","base","9","1912","1","0","0","0","0","0"
"admin","base","10","1915","1","0","0","1","0","0"
"admin","base","11","1912","1","0","0","0","0","0"
"admin","base","12","1915","1","3","1","0","0","0"
"admin","base","13","1912","1","0","0","0","0","0"
"admin","base","14","1915","1","1","1","0","0","0"
"admin","base","15","1912","1","0","0","0","0","0"
"admin","base","16","1915","1","1","1","0","0","0"
"admin","base","17","1912","1","0","0","0","0","0"
"admin","base","18","1915","1","0","0","1","0","0"
"admin","base","19","1912","1","0","0","0","0","0"
"admin","base","20","1915","1","4","1","0","0","0"
"admin","base","21","1912","1","0","0","0","0","0"
"admin","base","22","1915","1","2","1","0","0","0"
"admin","base","23","1912","1","0","0","0","0","0"
"admin","base","24","1915","1","13","1","0","0","0"

The error I receive is:

SKU 17288 - 1 SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'value_id' at row 1 -
SKU 17288 - 2 SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'value_id' at row 1 - ERROR ON RECORD #17046
SKU 17289 - 3 SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'value_id' at row 1 -
SKU 17289 - 4 SQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'value_id' at row 1 - ERROR ON RECORD #17047"

Surprisingly if I issue a mariadb restart  ("service mariadb restart") the problem seems to go away for some seconds...magmi begin is import correctly this time but after a while the problem reappear.

I have no clue about where to investigate / which could be the cause.

Any help will be appreciated.

Thank you.

**Comment by stefano-crosatti** [comment]
I found the cause and it's not magmi related, sorry for opening a non existent issue.

Thanks

**Comment by jmlagace** [comment]
And what was your not magmi related issue? I'm having exactly the same problem at the moment.

**Comment by mercurioweb** [comment]
Hi jmlagace can you solve? i've same problem :(

**Comment by jsp123** [comment]
I also had this problem. I changed the value_id to be a big int and set the length higher than the 11 and then it worked again.
