### ISSUE TITLE
Undefined index: token after replacing all files 

### ISSUE THREAD

**Issue by oMikR0n** [dweeves/magmi-git#323]
I tried to replace all files from here on the latest release of sourceforge but i now get the following error:
```
Notice: Undefined index: token in /public_html/magmi/web/security.php on line 13
RTK:
```

**Comment by dweeves** [comment]
maybe installing it in a new directory with a git clone should fix the problem

**Comment by dweeves** [comment]
fixed all panels from "old" web interface to use token in ajax requests. should fix the problem
