### ISSUE TITLE
Low import performance under magento1.9.x

### ISSUE THREAD

**Issue by sali1987** [dweeves/magmi-git#325]
We have 800.000-900.000 items in our store.
After we migrated our magento from 1.5 to 1.9 and we updated magmi to 0.7.19 from 0.7.12.
noticed that the importing speed fallen dramatically under 1-3 products / sec from about 500 products / sec.

Now we have to use the old version to keep performance, but if you can investigate the issues that would be great.
Thanks

**Comment by seb4C** [comment]
use latest git  master instead,(i suppose you upgraded from 0.7.19 to 0.7.21) , it should perform much better.

**Comment by sali1987** [comment]
Thanks for your quick response. 
We installed magmi with composer. Based on the release note file we use 0.7.19. 
In the composer.json we use:
"require": {
        "dweeves/magmi": "0.7.*"
    },
We tried to use the latest version what you said like this:
"require": {
        "dweeves/magmi": "0.7.21"
    },
but composer said there is nothing to update...

**Comment by MrGekko** [comment]
Try:
"require": {
"dweeves/magmi": "dev-master"
},

**Comment by sali1987** [comment]
Thanks! It solved our issue, now it works fine!
