### ISSUE TITLE
Value Replacer not using global multiselect seperator 

### ISSUE THREAD

**Issue by vikaskalra** [dweeves/magmi-git#326]
I have set the multiselect seperator as "|" as per the screenshot below:

![screenshot at sep 08 10-55-36](https://cloud.githubusercontent.com/assets/6917757/9724290/2a0b1c22-5618-11e5-82a9-f87f2e8727d5.png)

My CSV file looks like the below and value "        7,203.64" is only picking up as 7 and not 7203.64 so in the value replacer i put {{ {item.msrp}*1.1 }} it returns 7.7 instead of 7924.00. I feel it is because it is not pick up the universal multi select separator.
 
StockCode,Vendor,VendorStockCode,StockDescription,PrimaryCategory,SecondaryCategory,TertiaryCategory,RRPEx,DealerEx,StockAvailable,ETA,Status,Type,bundle1,bundle2,bundle3,bundle4,bundle5

AAAAA,BBBBB,CCCCC,"DDDDDDD",EEEE,"FFFFFF","GGGGG","        7,203.64","        5,498.90",0,TBA,A,bundle,,,,,

Are you able to fix the issue or advise on how it can be fixed. I do not use any multi select operations.

**Comment by dweeves** [comment]
The problem is not due to multiselect separator but to your number format.
Magmi does not support "Excel like, localized number representation"

For all numerical valiues, magmi only performs a quick "," to "." replacement for decimal separator.

ie: 7,203.64  is the localized number representation of 7263.64 

So remove all your "," in your numerical values and it should solve your problem

**Comment by vikaskalra** [comment]
This is a feed from a supplier and I cannot change it. Anyway to replace characters in certain fields before importing. It would be good functionality to have and hopefully really simple to implement.

**Comment by dweeves** [comment]
Value replacer plugin is here for that

2015-09-08 9:15 GMT+02:00 vikaskalra <notifications@github.com>:

**Comment by vikaskalra** [comment]
You just solved my problem - just had to put this in the value replacer and it all worked well:
{{ preg_replace('/[,]/', '', {item.msrp})*1.1  }}

Thank you! :)
