### ISSUE TITLE
Concurrent downloads or executions of Magmi by command line

### ISSUE THREAD

**Issue by paglian** [dweeves/magmi-git#333]
I'd like to speed up the process of importing images from remote locations. Currently, I have 25k images and I'm wondering if there is any way to download two or more images simultaneously. The only idea I came up is to split the catalog in several CSV files and execute several instances of Magmi in parallel by command line. Is it supported? Any potential problem of doing that?

Thanks.

**Comment by seb4C** [comment]
i think the best option to speedup would be to create a big archive of your remote images (if you have access to the source) and deploy them to the target server and use "local" import for images.
I you don't have access to the source, you may use some "webscrapping" utility that would do the job with the list of URLs you have and then perform the import using "local" image import

**Comment by paglian** [comment]
I don't have access to the source but I like the idea of scraping the images with some tool or script and then using local import. Thanks.
