### ISSUE TITLE
Magmi import configurables don't associate simples

### ISSUE THREAD

**Issue by Sjerd** [dweeves/magmi-git#335]
Hey, I'm using the magmi import tool for importing large products files. first I import the simples with this csv file:

    websites,store,type,attribute_set,sku,name,meta_title,meta_description,image,small_image,thumbnail,image_label,small_image_label,thumbnail_label,price,description,categories,configurable_attributes,short_description,status,tax_class_id,visibility,manage_stock,use_config_manage_stock,maten,color,merk,geslacht
    bedrijfskleding,bedrijfskleding,simple,bedrijfskleding,top_1,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,4.02,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,[bedrijfskleding]/Petten & Accessoires,"maten,color",100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,Enabled,Enabled,Enabled,Enabled,Enabled,Unic Size,White,Beechfield,mixte
    bedrijfskleding,bedrijfskleding,simple,bedrijfskleding,top_2,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,4.02,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,[bedrijfskleding]/Petten & Accessoires,"maten,color",100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,Enabled,Enabled,Enabled,Enabled,Enabled,Unic Size,Black,Beechfield,mixte
    bedrijfskleding,bedrijfskleding,simple,bedrijfskleding,top_3,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,4.02,100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,[bedrijfskleding]/Petten & Accessoires,"maten,color",100% Drillkatoen. Velcro®-sluiting. 5 segmenten.,Enabled,Enabled,Enabled,Enabled,Enabled,Unic Size,Bottle Green,Beechfield,mixte

Then after that I import the configurables with this file:

   

     websites,store,type,attribute_set,sku,name,simples_skus,configurable_attributes,meta_title,meta_description,image,small_image,thumbnail,image_label,small_image_label,thumbnail_label,price,description,categories,short_description,status,tax_class_id,visibility,is_in_stock
    bedrijfskleding,bedrijfskleding,configurable,bedrijfskleding,topg_1,ULTIMATE - 5 SEGMENTEN,"top_1,top_2,top_3,top_4,top_5,top_6,top_7","maten,color",ULTIMATE - 5 SEGMENTEN,100% Drillkatoen. Velcro�-sluiting. 5 segmenten.,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,bedrijfskleding/B15_2013.jpg,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,ULTIMATE - 5 SEGMENTEN,4.02,100% Drillkatoen. Velcro�-sluiting. 5 segmenten.,[bedrijfskleding]/Petten & Accessoires,100% Drillkatoen. Velcro�-sluiting. 5 segmenten.,Enabled,Enabled,Enabled,1
    bedrijfskleding,bedrijfskleding,configurable,bedrijfskleding,topg_2,GRAND PRIX CAP,"top_8,top_9,top_10,top_11","maten,color",GRAND PRIX CAP,100% Twill katoen. Velcro� sluiting.,bedrijfskleding/B159_2013.jpg,bedrijfskleding/B159_2013.jpg,bedrijfskleding/B159_2013.jpg,GRAND PRIX CAP,GRAND PRIX CAP,GRAND PRIX CAP,6.72,100% Twill katoen. Velcro� sluiting.,[bedrijfskleding]/Petten & Accessoires,100% Twill katoen. Velcro� sluiting.,Enabled,Enabled,Enabled,1
    bedrijfskleding,bedrijfskleding,configurable,bedrijfskleding,topg_3,BALL MARK GOLF CAP,"top_12,top_13,top_14","maten,color",BALL MARK GOLF CAP,100% chino katoen. Zweetband in 100% polyester. Cool Max SFP40+. Sluiting met gesp. Magneet op de klep om de bal aanduider te hechten.,bedrijfskleding/B185_2013.jpg,bedrijfskleding/B185_2013.jpg,bedrijfskleding/B185_2013.jpg,BALL MARK GOLF CAP,BALL MARK GOLF CAP,BALL MARK GOLF CAP,8.78,100% chino katoen. Zweetband in 100% polyester. Cool Max SFP40+. Sluiting met gesp. Magneet op de klep om de bal aanduider te hechten.,[bedrijfskleding]/Petten & Accessoires,100% chino katoen. Zweetband in 100% polyester. Cool Max SFP40+. Sluiting met gesp. Magneet op de klep om de bal aanduider te hechten.,Enabled,Enabled,Enabled,1

My configurable options for the configurable item proccessor are:

    Perform simples/configurable link : Yes
    auto match simples skus before configurable: No
    Force simples visibility: Not visible individually 

And the file get's imported without error's and
the simples are set to not visible individually. The configurable products are also created.
The only problem is that the configurable products don't have the simples associated after the import. Does anyone know what isn't correct? i've searched far and wide but just can't find a solution to my problem.

**Comment by MitchellBouwman** [comment]
Did you manage to fix it? having the same issues.

**Comment by sammarcus** [comment]
Are you able to combine both into a single CSV? Several factors have to be true for the simple / configurable relationship to establish, you'll generally have more luck if they're all in one file.

**Comment by Sjerd** [comment]
Yes i was. I added quotes around the simples and configurables but noticed that the program i used allread did this for me if multiple items were comma seperated in one column. thus creating double quotes. Also every simple product needs to have an option for the configurable attributes. and the attribute has to be set to be created for configurable products and selected simple.
