### ISSUE TITLE
Undefined index: token in security.php on line 11

### ISSUE THREAD

**Issue by olmoszamudio** [dweeves/magmi-git#345]
I reinstall the last version twice, and after 2-3 imports magmi says me:

STK:30060182456165f48d9b348.81043381
Notice: Undefined index: token in /var/www/clients/client0/web1/web/mag-bm/web/security.php on line 11
RTK:

Any advice to fix this please?

**Comment by mstern07** [comment]
First check to make sure nothing is running in the database. 

My SQL Command.
SHOW FULL PROCESSLIST

Then run the magmi_cancel
/mag-bm/web/magmi_cancel.php
