### ISSUE TITLE
Magmi CLI - Division By Zero

### ISSUE THREAD

**Issue by mstern07** [dweeves/magmi-git#347]
Hi,
I am getting the below warning when I run via CLI, when I run via the web front-end I get no warnings errors. Any help would be greatly appreciated. Thanks in advance. 

**Command Run:**
C:\WINDOWS\system32>C:\xampp\php\php C:\xampp\htdocs\magento\magmi\cli\magmi.cli
.php -profile=default -mode=create -CSV:filename="C:\xampp\htdocs\magento\var\im
port\MagmiFormatFile.csv"

**Warning:**
Warning: Division by zero in C:\xampp\htdocs\magento\magmi\engines\magmi_product
importengine.php on line 1792

**CSV File**
attribute_set,type,sku,store,status,visibility,page_layout,tax_class_id
Sweatshirts,simple,B00007000,admin,1,1,1,1

**Log From Front End**
Startup
Running Magmi Product Import Engine v1.9.1 by dweeves
Import Profile:default
Import Mode:create
Attributeset update is enabled.
Generic mapper v0.0.6a - No custom mapping found
Performing Datasource Lookup...
Found 1 records, took 0.00094103813171387 sec
Configurable Item processor v1.3.7a - no options_container set, defaulting to :Block after product info
Standard Attribute Import v1.1 - Newly created items will have default values for columns:
Ajusted processed columns:10

**Runtime Infos**
Initialized attribute_set_infos!
Skus imported OK:1/1
On the fly category creator/importer v0.2.5 - Updating Category children count....

**Comment by oldgarvice** [comment]
We ran into this issue as well, it was caused by not inputting a value in the global parameter "Reporting step in %:" this didn't seem to prevent products from importing, but caused rather large error log files. We put 1, this got rid of the error.
<img width="956" alt="screen shot 2015-10-19 at 11 04 48 am" src="https://cloud.githubusercontent.com/assets/15159651/10591232/209eeee4-7683-11e5-8984-ec50c23f16e7.png">

**Comment by mstern07** [comment]
Thanks!

**Comment by metacognizance** [comment]
![alt text](http://i.imgur.com/rOvy2a9.png "Reporting step in %")

**Comment by fboutin-pmc** [comment]
Common, the problem is NOT fixed and it is that simple as to add a condition to validate the input.

```
if ($rstep > 0 && $this->_current_row % $rstep == 0) {
```
