### ISSUE TITLE
parse_ini_file() has been disabled for security reasons

### ISSUE THREAD

**Issue by Lhari** [dweeves/magmi-git#349]
I've run into an issue with a restrictive host, who has disabled parse_ini_file, I would prefer not to rewrite Magmi to get around this issue. Is there a valid solution to this issue?

**Comment by seb4C** [comment]
hmm, without parse_ini_file, magmi cannot read any of its configuration files.
so, you're stuck for now. you'll have to implement an ini file parser & make Magmi_Config class use it instead of parse_ini_file. This change should not be too difficult to achieve.

**Comment by Lhari** [comment]
I see, thank you.
