### ISSUE TITLE
Url Key Conflict check required

### ISSUE THREAD

**Issue by brainworker** [dweeves/magmi-git#363]
Hey @dweeves 
I am testing your Magmi tool v0.7.23 with latest edition of Magento EE. I come across following error and fix

**Error**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-97-0' for key 'UNQ_CAT_PRD_ENTT_URL_KEY_ENTT_ID_ATTR_ID_STORE_ID'

**Fix**
This error is caused by Magento new URL key changes which require unique url key for each store id. 
When I introduced following change  in "handleUrl_keyAttribute" method defined in /magmi/plugins/inc/magmi_defaultattributehandler.php 

" ON DUPLICATE KEY UPDATE `value`=VALUES(`value`)";

Above error was gone and Magmi updated url for existing products without any issue.

This may already be on your radar. Just wanted to let u know and others

thx

**Comment by dweeves** [comment]
thanks for spotting this, latest commit on master has a fix
