### ISSUE TITLE
Magmi not importing

### ISSUE THREAD

**Issue by jameswithers** [dweeves/magmi-git#372]
Using the [current] latest version (d460109c0a2e07d23acf9e01c358b188f906efcc). Have a CSV file with three rows, two columns, sku, and attribute_code (dropdown).

The products exist in Magento, with attribute_code assigned to the attribute set, but values for attribute_code are not imported, and not set on the product.

**Comment by dweeves** [comment]
If your attribute is handled by a specific extension, it may have a
specific attribute model which does not follow the standard behaviour of
magento. In such a case a specific plugin is needed to handle your
attribute and implementing what the extension expects.

2015-11-24 12:32 GMT+01:00 James Withers <notifications@github.com>:

**Comment by jameswithers** [comment]
The error was because the attributes had been created (using Magmi) with the backend_type empty. This had defaulted them to static, which meant that attribute values were not imported as they are skipped here: https://github.com/dweeves/magmi-git/blob/master/magmi/engines/magmi_productimportengine.php#L903
