### ISSUE TITLE
error Division by zero in

### ISSUE THREAD

**Issue by Phizik-PRO** [dweeves/magmi-git#400]
error.log apache
Got error 'PHP message: PHP Warning:  Division by zero in ...magmi/engines/magmi_productimportengine.php on line 1796

what could be the problem?

**Comment by dweeves** [comment]
what is the report step you did configure in global parameters ?

it MUST be > 0

**Comment by Phizik-PRO** [comment]
Exactly! Thank you! Install the new version, I forgot to fill out this option
