### ISSUE TITLE
Magmi - Magento 2 - Configure Global Parameters - 2.0.4 Drop Down Selection

### ISSUE THREAD

**Issue by januaryrain77** [dweeves/magmi-git#447]
Hi Dweeves or to anyone who work on the Magmi-Magento 2 project,

I am trying to save profile on Magmi UI. My site is on Magento 2. If we go to Configure Global Parameters , I can not see Magento 2.0.4 as the choice in the drop down selection.
On the Version field, I only see 1.9xx  to 1.3xx which version should I choose since magento 2 has a completely different tables.

Thank you so much in advance :)

**Comment by dweeves** [comment]
For now, magmi is not yet compatible with magento 2 tables. I need to find
time to do it. However one project commiter has started a fork that aims to
make magmi compatible with magento 2.


2016-04-25 18:31 GMT+02:00 januaryrain77 <notifications@github.com>:

**Comment by januaryrain77** [comment]
Hi Dweeves

Thank you so much for your response :) I'll wait for your release :)

**Comment by tagesjump** [comment]
https://github.com/tagesjump/magmi-m2

**Comment by manojeshopping** [comment]
Hi Dweeves,

When we can expect the release of Magmi for Magento2 as your tool save our lots of time during bulk upload.

Thanks for your effort towards making new magmi for magento2.

**Comment by tmotyl** [comment]
see https://github.com/macopedia/magmi-m2/ for m2 version
