### ISSUE TITLE
Update existing product failed

### ISSUE THREAD

**Issue by magejonas** [dweeves/magmi-git#475]
Current version is 0.7.22

When update existing product, except "websites", other attributes could not update.

Fixing:

When create new product:
Mandatory column in csv & header -> "store"

When update existing product:
"Store" column **MUST NOT** include

**Comment by mblarsen** [comment]
I use `websites` and `store` together all the time.

**Comment by magejonas** [comment]
using websites and store together do works, should be my attribute value set issue.
