### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by akamura** [dweeves/magmi-git#547]
After installing MAGMI in Magento root directory and configuring the .htaccess as suggested, the login appear to be working fine with username/pass "magmi", but soon after configuring the global parameters and hit the "save global parameters" button, a new login window popup.

I type the same "magmi" for username/password but the login popup don't close ending with error:

You must be logged in to use Magmi

**Comment by rapgithub** [comment]
after saved the config you will need to enter the username and password for your Magento admin panel, and not the default magmi credentials!

read here
http://www.ecinternet.com/documentation/Content/Connector-Install-Guide/Magento-Setup/Configuring-Magmi.htm
