### ISSUE TITLE
Magmi remote csv url

### ISSUE THREAD

**Issue by mohammadobaid1** [dweeves/magmi-git#569]
I am using magmi 0.7.18 . In data source url I want to fetch csv from remote url which is as under
http://xx.xx.xx.xx:8080/fetch.csv  . When I run profile it shows error that magmi couldn't fetch data from url . Any clue in which format remote url should be ? When I avigate to that url using normal browser it downloads file without any problem

**Comment by ivantuzov** [comment]
I have same problem, receive info that in Magmi download directory file not found.  Through browser can download file but through Magmi Remote CSV url its impossible (with and without Force Download). I just try local CSV file, all works. 
Please help.

**Comment by mohammadobaid1** [comment]
@ivantuzov  Now what I was thinking is to setup cronjob to download file into cpanel specific directory and set import local csv  . Then set another cronjob to run that magmi everyday . What you think about that ?

**Comment by mohammadobaid1** [comment]
Hey @ivantuzov try one thing . Create an empty file in that specific directory where you want magmi to download that file and see if magmi overwrite that file or not ?

**Comment by ivantuzov** [comment]
@mohammadobaid1 Magmi delete this file. I try copy original file too, but Magme delete both files from this directory magmi/plugins/base/datasources/csv/downloads/

**Comment by ivantuzov** [comment]
@mohammadobaid1 i think that issue with my hosting (where is installed Magmi) because with CURL i download 0kb file and in log i see "... connection refused" 
BR

**Comment by mohammadobaid1** [comment]
Yes @ivantuzov I am facing the same exact issue. I think its more like a cpanel issue. If you setup cronjob with curl command on it it will also show refused connection . Can you ask your hosting site whether they block curl or wget ?

**Comment by ivantuzov** [comment]
@mohammadobaid1 yes, problem was in my hosting (magmi hosted) with cpanel. I sent request to hosting support, they not answered yet but now WGET start working, and Magmi get remote CSV files normally! :)

Still waiting answer from hosting support.

**Comment by mohammadobaid1** [comment]
@ivantuzov  Great to hear that . What's your external url looks like ? My url is something like http://ec2-xx-xx-xxx-4.compute-1.amazonaws.com:8000/data.csv . Also did you make any changes in cpanel to run wget command ?

**Comment by mohammadobaid1** [comment]
Indeed it was cpanel issue blocking requests.
