### ISSUE TITLE
Magmi don't work in magento 2.3.7 and php 2.4

### ISSUE THREAD

**Issue by matteotestoni** [dweeves/magmi-git#597]
Hi @dweeves. Magmi don't work anymore. Do you  plan to continue development or no?

**Comment by FredericMartinez** [comment]
Use https://github.com/firegento/FireGento_FastSimpleImport2 instead

**Comment by tmotyl** [comment]
For Magento 2 version of Magmi try https://github.com/macopedia/magmi-m2/
