### ISSUE TITLE
Bundle Items Processor - Not saving bundle items

### ISSUE THREAD

**Issue by jackiellowery** [dweeves/magmi-git#78]
Using Magmi 0.7.19a and Magento 1.9.0.1. The bundle items show up for the bundled product in the Admin area, but they don't show up on the frontend until I save the product in Admin.

**Comment by schuss** [comment]
That workaround does indeed work - but it's a pretty tough workaround.  Opening the Bundle Items tab and hitting save is pretty time-consuming (and there's no easy way to tell which products have been updated from the Admin).  

I've been trying to figure out from mysql logs what updates are getting made on the Bundle Items tab when the product is saved but haven't been able to identify anything yet.

**Comment by igi8819** [comment]
I have the same issue.
I finally done with an isntaller (not the nicest way but works!, in the future somebody have to fix this in magmi)
My code:

+++++++++++++++++++++++++++++++++++++++++++++
$installer = $this;
$installer->startSetup();
Mage::app()->getStore()->setId(Mage_Core_Model_App::ADMIN_STORE_ID);

$allProduct = Mage::getModel('catalog/product')
    ->getCollection()
    ->addFieldToFilter('type_id', 'bundle');

foreach ($allProduct as $product) {
    $product->setCanSaveCustomOptions(true);
    $product->setCanSaveBundleSelections(true);
    $product->setAffectBundleProductSelections(true);
    $product->save();
}
Mage::app()->getStore()->setId(Mage_Core_Model_App::DISTRO_STORE_ID);
$installer->endSetup();
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by schuss** [comment]
Can you please explain a little bit how you solved it with the code above?  Are you running this instead of the standard Magmi bundle import, or is this something you are running afterward to fix the incomplete bundles Magmi is creating?

**Comment by igi8819** [comment]
No.
1) import product with magmi (simple product, bundle product)
2) reindex in admin (or in magmi, if you checked to reindex with magmi)
2) i created an installer (for one module- no matter where)
3) refreshed the product detail page (the option appeared)

**Comment by schuss** [comment]
Sorry, I'm new with Magmi so still not sure what you mean.  I get Steps 1 and 2, and then with your code above you created a Magmi plugin which you run?  Or is your code above something you added to another PHP script in Magento elsewhere?  Or standalone PHP that you are running via command line or a URL that post-processes the bundles?  Sorry to be confused.

**Comment by schuss** [comment]
I'm starting to understand your code and I think the answer to my question is the third thing - this is a standalone PHP script you are running after Magmi is complete?

**Comment by igi8819** [comment]
Not a magmi plugin. I created a simple magento module which has one installer which contains the above code, so you need to have magento programing skill to do this

**Comment by schuss** [comment]
Is that a module you would be willing to post into the Magento community for others to use?  :)

**Comment by igi8819** [comment]
Maybe :) but it will not be a big module. Just one red button which have to push after magmi import

**Comment by schuss** [comment]
That's my kind of module!  
![Image of Yaktocat](http://img4.wikia.nocookie.net/__cb20140616225721/fantendo/images/5/5f/Futurama-shut-up-and-take-my-money-card-34.jpg)

**Comment by igi8819** [comment]
Please send me your email i will explain what to do with my code.

**Comment by schuss** [comment]
schuss@gmail.com.   Thanks!!

**Comment by igi8819** [comment]
Guy,
I finnaly fixed it in Magmi, so no external moduel needed!

Steps:

1) Download 
download and put the modified file to its directory, 
download from there: https://github.com/igi8819/magmi

2) Modify the import csv file
IMPORTANT:
put these field in .csv file with values:
- price_view:  1 (0 = price range, 1= as low as)
- price_type: 0 (0 = dynamic, 1 = fixed)
- shipment_type:  0 (0 = together, 1 = Separately)
- sku_type: 0 (0 = dynamic, 1 = fixed)
- weight_type: 0 (0 = dynamic, 1 = fixed)
- options_container: container1 ( where product options can be displayed. container1 is higher up the page, near the price.
container2 is further down, below the description )

This fields is important in import csv file, so put there!!!!!

After modification put the modified file to the magmi var import directory, where magmi loads import files.

3) Setup magmi
Setup magmi settings (turn in bundle item processor)

4) Do import
Import with magmi (create new one and existing..)

5) Reindex and cache
Reindex all data (before this you have to turn in flat catalog in admin system)
Clear cache

6) Check frontend
Check category page, and product view page.

I put an example csv file. you can download from
https://github.com/igi8819/magmi/tree/master/examples
bundle exmaple file 

If you hava question pleasy reply here

**Comment by schuss** [comment]
This works perfectly!!  Thanks so much! 

I added the columns above to my magmi import as instructed:

sku_type	shipment_type	options_container	weight_type	price_type	price_view
1	0	container1	1	1	1

 and i used the Magmi Magento Reindexer option to run indexes after import

My test product showed up correctly without the manual re-save!  Awesome! 

igi8819  - you are the wind beneath my wings, lol, thanks!

**Comment by igi8819** [comment]
Your welcome! :)

**Comment by barryvdh** [comment]
So what did you fix? Perhaps submit a PR to the core?

**Comment by igi8819** [comment]
I dont submit to the core.
catalog_product_relation table is not being updated with the parent_id and child_id of the bundle product - so i fixed it, to insert to this table.

added this fields to the import file:
price_view, price_type, shipment_type, sku_type, weight_type, options_container.

**Comment by dweeves** [comment]
Added your fix in latest commit ,as well as default values for extra fields you listed !!! thanks for spotting & fixing !!!!!

**Comment by igi8819** [comment]
Your welcome

**Comment by cortopy** [comment]
@dweeves Would it be possible to add a couple of lines to the wiki about this? Currently shipment_type and	options_container are not mentioned in http://wiki.magmi.org/index.php?title=Bundle_Item_processor 

I've been having some problems while adding bundle products and adding these two lines has just fixed everything beautifully

So what about:

* '''shipment_type''': (bool) Optional. Whether options are shipped together (0) or separately (1) . Defaults to 0.
* '''options_container''': (string) Optional. The block where the option is to be displayed. In Magento default xml files, these blocks could be either container1 or container2 ('container1' is higher up the page, near the price. 'container2' is further down, below the description )
